parameter_defaults:
  CephPoolDefaultSize: 1
  CephPoolDefaultPgNum: 16
  CephAnsiblePlaybookVerbosity: 1
  CephAnsibleEnvironmentVariables:
    ANSIBLE_SSH_RETRIES: '6'
  CephAnsibleDiskConfig:
    devices:
      - /dev/vdb
    osd_scenario: lvm
    osd_objectstore: bluestore
  CephConfigOverrides:
    mon_clock_drift_allowed: 0.5
    osd_pool_default_min_size: 1
    mon_pg_warn_min_per_osd: 0
    mon_pg_warn_max_per_osd: 0
    mon_pg_warn_max_object_skew: 0
    mon_max_pg_per_osd: 1024
    #mon_osd_allow_primary_affinity: 1
    rgw_enable_usage_log: false
    journal_size: 5120
    max_open_files: 131072
  CephAnsibleExtraConfig:
    osd_recovery_op_priority: 1
    osd_recovery_max_active: 1
    osd_max_backfills: 1
    health_osd_check_delay: 40
    health_osd_check_retries: 30
    health_mon_check_retries: 10
    health_mon_check_delay: 20
    ceph_osd_docker_cpu_limit: 1
    ceph_osd_docker_memory_limit: 3g
    # Avoid timeout of podman pulling rhceph image from undercloud
    docker_pull_timeout: "600s"
  #CephStorageImage: overcloud-minimal
  # Dashboard does not work yet
  CephEnableDashboard: True
  CephDashboardAdminPassword: redhat
  # Enable automated image conversion of qcow2 images to raw if RBD is glance backend
  GlanceImageImportPlugins: ['image_conversion']
  # Block qcow2 image upload
  #ControllerExtraConfig:
  #  glance::config::api_config:
  #    image_format/disk_formats:
  #      value: "raw,iso"

