resource_registry:
  OS::TripleO::Services::LoginDefs: /usr/share/openstack-tripleo-heat-templates/deployment/login-defs/login-defs-baremetal.yaml

parameter_defaults:
  ExtraConfig:
    tripleo::haproxy::ssl_cipher_suite: ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
    tripleo::haproxy::ssl_options: no-sslv3 no-tls-tickets
    snmp::ro_community: verysecretcommunitystring
    snmp::ro_community6: verysecretipv6communitystring
  PasswordMaxDays: 365
  PasswordMinDays: 1
  PasswordMinLen: 5
  PasswordWarnAge: 7
  FailDelay: 4
  HorizonPasswordValidator: '^.{6,18}$'
  HorizonPasswordValidatorHelp: 'Password must be between 6 and 18 characters.'
  #KeystonePasswordRegex: '^(?=.*?[a-zA-Z])(?=.*?[0-9])(?=.*?[#?!@\\/<>[:;{}`|.,_=~+$%^&*-]).{8,}$'
  #KeystoneChangePasswordUponFirstUse: True
  ControllerExtraConfig:
    horizon::disable_password_reveal: false

